package com.example.tournament.test;

import com.example.tournament.model.Team;
import com.example.tournament.model.Player;
import com.example.tournament.model.TeamManager;

/**
 * Test to verify the fixes for:
 * 1. Autogenerated player IDs are displayed
 * 2. Team approval status is properly tracked
 */
public class PlayerIdAndApprovalTest {
    
    public static void main(String[] args) {
        try {
            System.out.println("=== Player ID and Approval Status Test ===\n");
            
            testPlayerIdDisplay();
            testApprovalStatusTracking();
            
            System.out.println("\n=== All Tests Passed ===");
            
        } catch (Exception e) {
            System.err.println("Test failed with error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }
    
    /**
     * Test that player toString() includes the ID in a user-friendly format
     */
    private static void testPlayerIdDisplay() {
        System.out.println("Test 1: Player ID Display");
        
        // Create player without ID (simulating new player)
        Player newPlayer = new Player("John Doe", 10, "Forward");
        String newPlayerStr = newPlayer.toString();
        assert newPlayerStr.contains("ID:") : "Player toString should include ID label";
        assert newPlayerStr.contains("N/A") : "New player should show N/A for ID";
        assert newPlayerStr.contains("Name:") : "Player toString should include Name label";
        assert newPlayerStr.contains("Jersey") : "Player toString should include Jersey number";
        assert newPlayerStr.contains("Position:") : "Player toString should include Position label";
        System.out.println("  New player: " + newPlayerStr);
        
        // Create player with ID (simulating persisted player)
        Player persistedPlayer = new Player("Jane Smith", 5, "Defender");
        persistedPlayer.setId(123L);
        String persistedPlayerStr = persistedPlayer.toString();
        assert persistedPlayerStr.contains("123") : "Persisted player should show actual ID";
        assert persistedPlayerStr.contains("Jane Smith") : "Player toString should include name";
        System.out.println("  Persisted player: " + persistedPlayerStr);
        
        System.out.println("  ✓ Player ID is displayed correctly in toString()");
    }
    
    /**
     * Test that team approval status is properly tracked
     */
    private static void testApprovalStatusTracking() {
        System.out.println("\nTest 2: Approval Status Tracking");
        
        TeamManager manager = new TeamManager("test_manager", "password", "test@example.com");
        Team team = new Team("Test Team", manager);
        
        // Check initial status
        assert team.getApprovalStatus() != null : "Approval status should not be null";
        assert "NOT_REQUESTED".equals(team.getApprovalStatus()) : 
            "Initial approval status should be NOT_REQUESTED, got: " + team.getApprovalStatus();
        System.out.println("  Initial status: " + team.getApprovalStatus());
        
        // Request approval
        team.RequestApproval();
        assert "PENDING".equals(team.getApprovalStatus()) : 
            "After RequestApproval, status should be PENDING, got: " + team.getApprovalStatus();
        System.out.println("  After RequestApproval: " + team.getApprovalStatus());
        
        // Simulate approval
        team.setApprovalStatus("APPROVED");
        assert "APPROVED".equals(team.getApprovalStatus()) : 
            "After approval, status should be APPROVED";
        System.out.println("  After approval: " + team.getApprovalStatus());
        
        // Test rejection scenario
        Team team2 = new Team("Test Team 2", manager);
        team2.RequestApproval();
        team2.setApprovalStatus("REJECTED");
        assert "REJECTED".equals(team2.getApprovalStatus()) : 
            "After rejection, status should be REJECTED";
        System.out.println("  After rejection: " + team2.getApprovalStatus());
        
        System.out.println("  ✓ Approval status tracking works correctly");
    }
}
